# This workflow will build a .NET project code
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o website
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4.4.3
      with:
        name: webapp
        path: website/**
        if-no-files-found: warn
  deploytodev: 
    runs-on: ubuntu-latest
    environment: dev
    needs: build 
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: webapp
        path: webapp
    - name: Deploy web app
      uses: azure/webapps-deploy@v2
      with:
        app-name: nttdatawebapp-dev-ape4anehfzdfg9b8
        publish-profile: ${{ secrets.AZURE_DEV_WEBAPP_PUBLISH_PROFILE  }}
        package: webapp 
  deploytoqa: 
    runs-on: ubuntu-latest
    environment: qa
    needs: deploytodev 
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: webapp
        path: webapp
    - name: Deploy web app
      uses: azure/webapps-deploy@v2
      with:
        app-name: nttdatawebapp-qa-gubjevbudqb6bchn
        publish-profile: ${{ secrets.AZURE_QA_WEBAPP_PUBLISH_PROFILE  }}
        package: webapp 
  deploytoprod: 
    runs-on: ubuntu-latest
    environment: production
    needs: deploytoqa 
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: webapp
        path: webapp
    - name: Deploy web app
      uses: azure/webapps-deploy@v2
      with:
        app-name: nttdatawebapp-edcsfkfbhdfradet
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: webapp 
  
