name: Deploy ASP.Net Core app to Azure Web App - mvsshellmultistagedeploymentgithub

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
   
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          run_id: 8
          name: mvsbuildartifact-8      
                   

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mvsshellmultistagedeploymentgithub'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D1252A560D1D45CD95B8DCE02611704C }}
          package: .
